In [2]:
import numpy as np

* 行列

In [5]:
print(np.array([1,2,3,4]))
print(np.array([[1,2,3,4],[5,6,7,8]]))

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


* 転置行列

In [9]:
X = np.array([[1,2,3,4],[5,6,7,8]])
print(X.shape)
print(X)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [10]:
X = X.T
print(X.shape)
print(X)

(4, 2)
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


* 行列の積
  * MxN行列とNxL行列の積はMxL行列となる
  * お互いのNは一致させる必要がある

In [11]:
#2x3行列, 3x2行列の積
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,2],[3,4],[5,6]])
np.dot(X, Y)

array([[22, 28],
       [49, 64]])

* トレース
  * 対角成分の和
$$tr A = \Sigma a_{ii}$$

In [24]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.diag(X).sum()

15

* 対称行列
$$A=A^{T}$$

In [12]:
X = np.array([[1,2,3],[2,3,8],[3,8,9]])
X

array([[1, 2, 3],
       [2, 3, 8],
       [3, 8, 9]])

In [13]:
X.T

array([[1, 2, 3],
       [2, 3, 8],
       [3, 8, 9]])

In [15]:
np.all(X == X.T)

True

* 単位行列
  * 対角成分がすべて1の対角行列（対角成分以外0）のこと。
  * n次の正則行列Aとn次の単位行列Iについて、AI = IA =Aが成り立つ。

In [16]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
A = np.array([[1,2,3],[4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.dot(A,I)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
np.dot(I,A)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

* 直行行列
$$AA^{T} = I $$

In [20]:
th = np.pi/4
A = np.array([[np.cos(th), -np.sin(th)],
              [np.sin(th), np.cos(th)]])
A

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [21]:
A.T

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [22]:
A.dot(A.T)

array([[1., 0.],
       [0., 1.]])

* 逆行列
  * n次の行列Aが逆行列をもつとき次の関係はすべて同値
    * Aの行列式(det) ≠ 0
    * Aのランク = n
    * Aは正則行列
    * Aの各行を構成するベクトルは一次独立
    * Aの各列を構成するベクトルは一次独立

In [27]:
A = np.array([[3,2,5],[2,1,5], [4,6,0]])
A

array([[3, 2, 5],
       [2, 1, 5],
       [4, 6, 0]])

In [31]:
np.linalg.det(A)

-10.000000000000002

In [41]:
np.linalg.matrix_rank(A)

3

In [32]:
Ai = np.linalg.inv(A)
Ai

array([[ 3. , -3. , -0.5],
       [-2. ,  2. ,  0.5],
       [-0.8,  1. ,  0.1]])

In [33]:
np.dot(A, Ai)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.dot(Ai, A)

array([[ 1.00000000e+00, -1.77635684e-15,  0.00000000e+00],
       [ 8.88178420e-16,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  4.44089210e-16,  1.00000000e+00]])

* 積の逆行列
$$ (XY)^{-1} = Y^{-1}X^{-1}$$

In [35]:
X = np.array([[-3, 3],[-4, 1]])
Y = np.array([[1, 4], [-3, 5]])

In [36]:
np.linalg.inv(np.dot(X,Y))

array([[-0.07189542, -0.01960784],
       [ 0.04575163, -0.07843137]])

In [37]:
np.dot(np.linalg.inv(Y), np.linalg.inv(X))

array([[-0.07189542, -0.01960784],
       [ 0.04575163, -0.07843137]])

* 積の転置行列
$$ (XY)^{T} = Y^{T}X^{T}$$

In [38]:
X = np.array([[-3, 3],[-4, 1]])
Y = np.array([[1, 4], [-3, 5]])

In [39]:
np.dot(X,Y).T

array([[-12,  -7],
       [  3, -11]])

In [40]:
np.dot(Y.T,X.T)

array([[-12,  -7],
       [  3, -11]])

* 転置行列の行列式
$$detX=detX^{T} $$

In [43]:
X = np.array([[-3, 3],[-4, 1]])
np.linalg.det(X)

8.999999999999998

In [44]:
np.linalg.det(X.T)

9.000000000000002

* 行列の積の行列式
$$det(XY)=detXdetY $$

In [45]:
X = np.array([[-3, 3],[-4, 1]])
Y = np.array([[1, 4], [-3, 5]])
np.linalg.det(np.dot(X,Y))

152.99999999999997

In [46]:
np.linalg.det(X)*np.linalg.det(Y)

152.99999999999997

* 逆行列の行列式
$$ detX^{-1} = \frac{1}{detX}$$

In [48]:
X = np.array([[-3, 3],[-4, 1]])
np.linalg.det(np.linalg.inv(X))

0.11111111111111115

In [49]:
1/np.linalg.det(X)

0.11111111111111113

* 三角行列の行列式
  * 対角成分の積に一致する

In [50]:
X = np.array([[-3, 3, 5],[0, 1, 3],[0, 0, 7]])
X

array([[-3,  3,  5],
       [ 0,  1,  3],
       [ 0,  0,  7]])

In [54]:
np.linalg.det(X)

-21.0

In [53]:
np.diag(X).prod()

-21

* 固有値問題
 * 固有ベクトルはAを掛けても方向が変わらないベクトル

In [25]:
A = np.array([[1, 1], [0, 2]])
A

array([[1, 1],
       [0, 2]])

In [28]:
w, v = np.linalg.eig(A)
w, v

(array([1., 2.]), array([[1.        , 0.70710678],
        [0.        , 0.70710678]]))

In [36]:
np.dot(A, v[:, 1])

array([1.41421356, 1.41421356])

In [40]:
#対角化
np.dot(np.dot(np.linalg.inv(v), A), v)

array([[1., 0.],
       [0., 2.]])